### ISSUE TITLE
fs.exists is slated to be removed

### ISSUE THREAD

**Issue by nubs** [busterc/assert-dotenv#2]
fs.exists is considered an antipattern and is documented as a potential deprecation in the [documentation](https://nodejs.org/api/fs.html#fs_fs_exists_path_callback).  It seems like it should be possible to just do the read and handle the error appropriately.

I personally find that a bit funky although it likely makes sense in this particular use case.

**Comment by busterc** [comment]
removed from v3 904eeafcca8971848d6d15f128943cfb3f4a9f20

**Comment by nubs** [comment]
Thanks Buster :)
