### ISSUE TITLE
Async behavior can cause problems

### ISSUE THREAD

**Issue by nubs** [busterc/assert-dotenv#3]
The client code would be a lot cleaner if this could be done synchronously rather that async as there would be no need for a callback.  There are also cases where different runners (e.g., gulp, mocha) seem to expect things to be run immediately and they register nextTick handlers to process their stuff.  This doesn't work with the async callback.

It should be possible to switch this to a synchronous API using the `fs.*Sync` calls.  `find-parent-dir` also offers a synchronous API that can be used.

The expected result of this would be changing this:
```js
require('assert-dotenv')({}, function() {
  // some code
});
```

into this:
```js
require('assert-dotenv')({});
// some code
```

**Comment by axelboc** [comment]
+1

I'm having trouble making it work with Gulp. Generally speaking, the asynchronicity doesn't benefit many scenarios, and the extra callback does clutter the server code. Perhaps instead of replacing the current behaviour entirely, a new method or config option could simply be added to the API?

**Comment by busterc** [comment]
904eeafcca8971848d6d15f128943cfb3f4a9f20 v3 now fully supports proper sync and async.  See README.md for examples.

**Comment by nubs** [comment]
Awesome!

**Comment by axelboc** [comment]
Thanks!
